name: Android APK Derleyici
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodları Çek
        uses: actions/checkout@v4

      - name: Java JDK 17 Kurulumu
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Eksik Gradle Dosyalarını Otomatik Üret
        run: |
          if [ ! -f gradlew ]; then
            echo "gradlew bulunamadı, yeniden oluşturuluyor..."
            gradle wrapper --gradle-version 8.2
          fi

      - name: Gradle Yetkilerini Ayarla
        run: chmod +x gradlew

      - name: APK Derle (Temiz ve Önbelleksiz Kurulum)
        run: ./gradlew assembleDebug --no-daemon --no-build-cache

      - name: APK Dosyasını Çıkart
        uses: actions/upload-artifact@v4
        with:
          name: manga-translate-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
          
